#!/bin/sh

sketch_app_dir=`mdfind kMDItemCFBundleIdentifier == 'com.bohemiancoding.sketch3' | head -n 1`
sketch_tool=$sketch_app_dir/Contents/Resources/sketchtool/bin/sketchtool

sketch_modified_at=`stat -f "%m" "$1"`
svg_modified_at=0
if [ -d "$2" ]; then
  svg_modified_at=`stat -f "%m" "$2"/* | sort -rn | head -1 | cut -f2-`
fi

if [ "$sketch_modified_at" -gt "$svg_modified_at" ]; then
  # Export SVGs from Sketch
  $sketch_tool \
    export slices \
    "$1" \
    --formats=svg \
    --output="$2"

  # Convert strokes to paths
  svg-stroke-to-path SameStrokeColor 'stroke="#000"' "$2"/*.svg
fi

# Delete the "generated" font
rm -f "$4"

# From the "base" font, import SVGs and save as the "generated" font
fontforge-svg-importer "$3" "$4" "$2"/*.svg
